insert into exercises (name, kind, primary_muscle, equipment)
values
  ('Back Squat', 'weight_reps', 'quads', 'barbell'),
  ('Front Squat', 'weight_reps', 'quads', 'barbell'),
  ('Paused Squat', 'weight_reps', 'quads', 'barbell'),
  ('Deadlift', 'weight_reps', 'posterior chain', 'barbell'),
  ('Romanian Deadlift', 'weight_reps', 'hamstrings', 'barbell'),
  ('Bench Press', 'weight_reps', 'chest', 'barbell'),
  ('Incline Bench Press', 'weight_reps', 'chest', 'barbell'),
  ('Overhead Press', 'weight_reps', 'shoulders', 'barbell'),
  ('Push Press', 'weight_reps', 'shoulders', 'barbell'),
  ('Pendlay Row', 'weight_reps', 'back', 'barbell'),
  ('Lat Pulldown', 'weight_reps', 'back', 'cable'),
  ('Leg Press', 'weight_reps', 'quads', 'machine'),
  ('Leg Extension', 'weight_reps', 'quads', 'machine'),
  ('Leg Curl', 'weight_reps', 'hamstrings', 'machine'),
  ('Hip Thrust', 'weight_reps', 'glutes', 'barbell'),
  ('Seated Cable Row', 'weight_reps', 'back', 'cable'),
  ('Dumbbell Bench Press', 'weight_reps', 'chest', 'dumbbell'),
  ('Dumbbell Row', 'weight_reps', 'back', 'dumbbell'),
  ('Walking Lunge', 'weight_reps', 'quads', 'dumbbell'),
  ('Calf Raise', 'weight_reps', 'calves', 'machine'),
  ('Push-up', 'bodyweight_reps', 'chest', 'bodyweight'),
  ('Air Squat', 'bodyweight_reps', 'quads', 'bodyweight'),
  ('Sit-up', 'bodyweight_reps', 'core', 'bodyweight'),
  ('Crunch', 'bodyweight_reps', 'core', 'bodyweight'),
  ('Bodyweight Split Squat', 'bodyweight_reps', 'quads', 'bodyweight'),
  ('Dip', 'bodyweight_reps', 'triceps', 'bodyweight'),
  ('Burpee', 'bodyweight_reps', 'full body', 'bodyweight'),
  ('Mountain Climber', 'bodyweight_reps', 'core', 'bodyweight'),
  ('Step-up', 'bodyweight_reps', 'glutes', 'bodyweight'),
  ('Inverted Row', 'bodyweight_reps', 'back', 'bodyweight'),
  ('Weighted Pull-up', 'weighted_bodyweight', 'back', 'belt'),
  ('Weighted Chin-up', 'weighted_bodyweight', 'back', 'belt'),
  ('Weighted Dip', 'weighted_bodyweight', 'chest', 'belt'),
  ('Weighted Push-up', 'weighted_bodyweight', 'chest', 'plate'),
  ('Assisted Pull-up', 'weighted_bodyweight', 'back', 'machine'),
  ('Assisted Dip', 'weighted_bodyweight', 'triceps', 'machine'),
  ('Belt Squat March', 'weighted_bodyweight', 'quads', 'belt'),
  ('Weighted Step-up', 'weighted_bodyweight', 'glutes', 'vest'),
  ('Weighted Plank Reach', 'weighted_bodyweight', 'core', 'vest'),
  ('Weighted Walking Lunge', 'weighted_bodyweight', 'quads', 'vest'),
  ('Plank', 'duration', 'core', 'bodyweight'),
  ('Side Plank', 'duration', 'obliques', 'bodyweight'),
  ('Wall Sit', 'duration', 'quads', 'bodyweight'),
  ('Dead Hang', 'duration', 'grip', 'bodyweight'),
  ('Farmer Hold', 'duration', 'grip', 'dumbbell'),
  ('Hollow Hold', 'duration', 'core', 'bodyweight'),
  ('Running', 'distance_duration', 'cardio', 'none'),
  ('Rowing', 'distance_duration', 'cardio', 'erg'),
  ('Cycling', 'distance_duration', 'cardio', 'bike'),
  ('Walking', 'distance_duration', 'cardio', 'none'),
  ('Ski Erg', 'distance_duration', 'cardio', 'erg')
on conflict do nothing;
